name: Autolog CI Workflow

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.0.0

    - name: Set up JDK 11
      uses: actions/setup-java@v1.3.0
      with:
        java-version: 11.0.5

    - name: Build with Maven
      run: mvn -B package verify
