name: Autolog Release Workflow

on:
  push:
    branches:
      - master

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.1.0

      - name: Set up JDK 11
        uses: actions/setup-java@v1.3.0
        with:
          java-version: 11.0.5

      - name: Get release version from POM file
        run: echo ::set-env name=RELEASE_VERSION::$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)

      - name: Build, sign and deploy artifacts to Maven Central (OSSRH)
        run: |
          echo "Import the GPG key..."
          echo "${{ secrets.GPG_KEY }}" | base64 -d > gpg_private.key
          gpg --batch --pinentry-mode loopback --import ./gpg_private.key
          rm ./gpg_private.key
          echo "Deploy to OSSRH..."
          mvn -B deploy -Prelease -Dgpg.passphrase=${{ secrets.GPG_PASSPHRASE }}

      - name: Build bundled artifacts with Maven
        run: mvn -B clean package -Pbundle

      - name: Create GitHub release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "autolog-core/target/autolog-core-${{ env.RELEASE_VERSION }}-bundle.jar,autolog-spring/target/autolog-spring-${{ env.RELEASE_VERSION }}-bundle.jar"
          name: "${{ env.RELEASE_VERSION }}"
          tag: "v${{ env.RELEASE_VERSION }}"
          draft: true
          token: ${{ secrets.GITHUB_TOKEN }}